### ISSUE TITLE
Bug in the Link-Template URL rewrite?

### ISSUE THREAD

**Issue by phochste** [MellonScholarlyCommunication/scholarly-browser#5]
I think there is a bug in the way how for a service node the value of the `Link-Template` should be rewritten when a `{url}` template is available.

Use:

- Artifact URL: http://193.190.80.48:56633/service/r/artifacts/artifact1.html
- Service Mode URL: http://193.190.80.48:56633/service/e/

I get in the console an error message:

```
ActorHttpFetch.ts:59 
        
        
       GET http://193.190.80.48:56633/service/e/events/http://193.190.80.48:56633/service/r/artifacts/artifact1.html.log%22 net::ERR_FAILED 404 (Not Found)
```

Notice the extra `%22` at the end of the URL which shouldn't be there.

**Comment by smessie** [comment]
Thanks for reporting! The issue was that there was a space before the semicolon in the Link-Template (`Link-Template: "http://193.190.80.48:56633/service/e/events/{url}.log" ; rel="eventlog"`), however it should not fail on that. I have made the artifact-explorer more robust, and this issue should no longer appear.
